# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Enable gradlew execution
        run: chmod +x ./gradlew

      - name: Gradle Build
        run: ./gradlew build

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'build/libs/*.jar, !build/libs/*-sources.jar'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
